### ISSUE TITLE
Uncaught TypeError: Cannot read property 'questions' of undefined error

### ISSUE THREAD

**Issue by BaksoKeras** [gbaranski/quizizz-cheat#18] opened 2021-02-21 10:38 UTC
i don't know why but the first script isn't working for me

![image](https://user-images.githubusercontent.com/54498719/108622459-8c5a8f80-746b-11eb-9bbd-a5e060ecff6a.png)

**Comment by gbaranski** [comment] 2021-02-21 12:12
Duplicate of #16 #8

**Closed as completed by gbaranski** 2021-02-21 12:12 UTC
Labels: duplicate
