### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by tofonek** [gbaranski/quizizz-cheat#26] opened 2021-03-24 10:53 UTC
Hello, quizizz script don't work
![image](https://user-images.githubusercontent.com/46074679/112298772-7c66e300-8c97-11eb-9fd9-cefe3ef92f03.png)

**Comment by gbaranski** [comment] 2021-03-24 13:32
duplicate of #8

**Closed as completed by gbaranski** 2021-03-24 13:32 UTC
Labels: duplicate
