### ISSUE TITLE
This isn't compatible with test mode on quizizz...

### ISSUE THREAD

**Issue by iu18** [gbaranski/quizizz-cheat#33] opened 2021-05-20 19:30 UTC
Just writes endless errors to the console to the point I can't open it anymore. Seems to just endlessly read from something that doesn't exist on test mode but exists on regular mode. This should either exit on _**X**_ number of fails of reading, or have it read it fixed to read it correctly.

**Comment by gbaranski** [comment] 2021-11-02 18:29
duplicate of #29

**Closed as completed by gbaranski** 2021-11-02 18:29 UTC
