### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by Jheycit** [gbaranski/quizizz-cheat#20] opened 2021-02-28 18:04 UTC
When putting the code, I get this error, could you help me to solve it right here, without sending me to other answers, thanks

![WhatsApp Image 2021-02-23 at 7 47 58 PM](https://user-images.githubusercontent.com/79805048/109428478-4b133400-79c5-11eb-9942-e3bc55a06e95.jpeg)

**Comment by gbaranski** [comment] 2021-02-28 20:31
duplicate of #8

**Closed as completed by gbaranski** 2021-02-28 20:31 UTC
Labels: duplicate
